### ISSUE TITLE
Missing Sign-Up Form/Route

### ISSUE THREAD

**Issue by MaryRichelle** [in-tech-gration/kiptrak-cloud#8]
I’ve noticed that there is currently no sign-up form or route in development. 
Suggestion: Add a sign-up form with an email/password Include options for signing up with GitHub.

**Comment by kostasx** [comment]
Currently, we want the registration/sign-up process to be manual. Students will first apply through our form and then we can manually add their accounts on Supabase. 

The process will remain manual for the time being.
